// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type Event struct {
	ID          string      `json:"id"`
	CreatedAt   string      `json:"createdAt"`
	LastUpdated string      `json:"lastUpdated"`
	Name        string      `json:"name"`
	Days        []*EventDay `json:"days"`
}

type EventDay struct {
	ID          string   `json:"id"`
	CreatedAt   string   `json:"createdAt"`
	LastUpdated string   `json:"lastUpdated"`
	StartAt     string   `json:"startAt"`
	EndAt       string   `json:"endAt"`
	Rounds      []*Round `json:"rounds"`
}

type EventInput struct {
	Name string `json:"name"`
}

type Match struct {
	ID      string    `json:"id"`
	Players []*Player `json:"players"`
}

type Player struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	User *User  `json:"user"`
}

type Round struct {
	ID      string   `json:"id"`
	Counter int      `json:"counter"`
	Matches []*Match `json:"matches"`
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Name     string  `json:"name"`
	Picture  *string `json:"picture"`
}
